name: Auto Bump Cask Versions

on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12:00 UTC
  workflow_dispatch:
    inputs:
      tap_name:
        description: 'Tap name (e.g., SoloAntonio/cartero)'
        required: false
        default: 'soloantonio/cartero'
      tap_url:
        description: 'Tap URL'
        required: false
        default: 'https://github.com/SoloAntonio/homebrew-cartero'
      casks:
        description: 'Cask names to check (space separated, leave empty for all)'
        required: false
        default: ''

env:
  TAP_NAME: ${{ github.event.inputs.tap_name || 'soloantonio/cartero' }}
  TAP_URL: ${{ github.event.inputs.tap_url || 'https://github.com/SoloAntonio/homebrew-cartero' }}

jobs:
  auto-bump:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Setup Homebrew tap
        run: |
          echo "Using tap: ${{ env.TAP_NAME }} (${{ env.TAP_URL }})"
          brew tap ${{ env.TAP_NAME }} ${{ env.TAP_URL }}
          brew update
          brew developer on

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [ -z "$GH_TOKEN" ]; then
            echo "::error::GH_TOKEN is not set"
            exit 1
          fi
          gh auth status || gh auth login --with-token <<< "$GH_TOKEN"

      - name: Find casks to check
        id: find_casks
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

          if [ -n "${{ github.event.inputs.casks }}" ]; then
            echo "Checking specified casks: ${{ github.event.inputs.casks }}"
            echo "casks=$(echo '${{ github.event.inputs.casks }}' | tr ' ' '\n' | jq -R . | jq -cs .)" >> "$GITHUB_OUTPUT"
          else
            CASKS=$(find Casks -name "*.rb" -exec basename {} .rb \; | jq -R . | jq -cs .)
            echo "Found casks to check: $CASKS"
            echo "casks=$CASKS" >> "$GITHUB_OUTPUT"
          fi

      - name: Process casks
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CASKS: ${{ steps.find_casks.outputs.casks }}
        shell: bash
        run: |
          #git config --global user.name "GitHub Action"
          #git config --global user.email "action@github.com"

          echo "$CASKS" | jq -r '.[]' > cask_list.txt

          while IFS= read -r CASK_NAME; do
            echo "::group::Processing: $CASK_NAME"
            CASK_PATH="Casks/$CASK_NAME.rb"

            if [ ! -f "$CASK_PATH" ]; then
              echo "::warning::Cask file not found: $CASK_PATH"
              continue
            fi

            # Run brew livecheck and capture JSON
            if ! LIVECHECK_JSON=$(brew livecheck --tap soloantonio/cartero --cask --quiet --full-name --json "$CASK_NAME" 2>/dev/null); then
              echo "::warning::brew livecheck failed for $CASK_NAME. Skipping."
              echo "::endgroup::"
              continue
            fi

            # Validate JSON structure
            if ! echo "$LIVECHECK_JSON" | jq -e '.[0].version' >/dev/null 2>&1; then
              echo "::warning::Invalid JSON structure from livecheck for $CASK_NAME. Skipping."
              echo "::endgroup::"
              continue
            fi

            # Extract fields
            CURRENT_VERSION=$(echo "$LIVECHECK_JSON" | jq -r '.[0].version.current // empty')
            LATEST_VERSION=$(echo "$LIVECHECK_JSON" | jq -r '.[0].version.latest // empty')
            IS_OUTDATED=$(echo "$LIVECHECK_JSON" | jq -r '.[0].version.outdated')

            if [ -z "$CURRENT_VERSION" ]; then
              echo "::warning::Missing current version in livecheck result for $CASK_NAME. Skipping."
              echo "::endgroup::"
              continue
            fi

            echo "Current version: $CURRENT_VERSION"
            echo "Latest version: $LATEST_VERSION"
            echo "Outdated: $IS_OUTDATED"

            # Skip if up to date
            if [ "$IS_OUTDATED" != "true" ]; then
              echo "No update for $CASK_NAME (outdated: $IS_OUTDATED)"
              echo "::endgroup::"
              continue
            fi

            echo "Current version: $CURRENT_VERSION"
            echo "Latest version: $LATEST_VERSION"
            echo "Outdated: $IS_OUTDATED"

            # Skip if up to date
            if [ "$IS_OUTDATED" != "true" ]; then
              echo "No update for $CASK_NAME (outdated: $IS_OUTDATED)"
              continue
            fi

            BRANCH="bump-$CASK_NAME-$LATEST_VERSION"
            git checkout -B "$BRANCH"

            # Extract first url line
            URL_LINE=$(grep -m 1 '^[[:space:]]*url "' "$CASK_PATH") 

            # Extract the URL inside the quotes, remove trailing comma
            URL_TEMPLATE=$(echo "$URL_LINE" | sed -E 's/^[[:space:]]*url "([^"]+)",$/\1/')

            # Replace version placeholder #{version} with actual LATEST_VERSION
            URL_TEMPLATE="${URL_TEMPLATE//\#\{version\}/$LATEST_VERSION}"

            # Replace arch placeholder #{arch} for arm and x64
            URL_ARM="${URL_TEMPLATE//\#\{arch\}/arm64}"
            URL_X64="${URL_TEMPLATE//\#\{arch\}/x64}"

            echo "Downloading ARM binary from $URL_ARM"
            if ! curl -L -f -o arm.dmg "$URL_ARM"; then
              echo "::error::Failed to download ARM binary"
              git checkout main
              git branch -D "$BRANCH" || true
              echo "::endgroup::"
              continue
            fi

            echo "Downloading Intel binary from $URL_X64"
            if ! curl -L -f -o intel.dmg "$URL_X64"; then
              echo "::error::Failed to download Intel binary"
              rm -f arm.dmg
              git checkout main
              git branch -D "$BRANCH" || true
              echo "::endgroup::"
              continue
            fi

            # Calculate SHA256 checksums
            ARM_SHA=$(shasum -a 256 arm.dmg | awk '{print $1}')
            INTEL_SHA=$(shasum -a 256 intel.dmg | awk '{print $1}')

            echo "ARM SHA256: $ARM_SHA"
            echo "Intel SHA256: $INTEL_SHA"

            # Clean up
            rm -f arm.dmg intel.dmg

            # Update cask file version
            sed -i '' -E "s/^[[:space:]]*version \"[^\"]+\"/  version \"$LATEST_VERSION\"/" "$CASK_PATH"

            # Update sha256 checksums for arm and intel
            sed -i '' -E "s/^(  sha256 arm:[[:space:]]+\")[a-f0-9]+\"/\1$ARM_SHA\"/" "$CASK_PATH"
            sed -i '' -E "s/^(         intel:[[:space:]]+\")[a-f0-9]+\"/\1$INTEL_SHA\"/" "$CASK_PATH"

            echo "Installing local cask to verify: $CASK_PATH"
            if brew install --cask "./$CASK_PATH"; then
              git add "$CASK_PATH"
              git commit -m "$CASK_NAME: Update to version $LATEST_VERSION"
              git push -u origin "$BRANCH"

              PR_BODY="Auto-bumped $CASK_NAME to $LATEST_VERSION"
              PR_URL=$(gh pr create --title "$CASK_NAME: Update to version $LATEST_VERSION" \
                                    --body "$PR_BODY" \
                                    --base main \
                                    --head "$BRANCH")

              echo "PR created: $PR_URL"
              PR_NUMBER=$(basename "$PR_URL")
              
              if gh pr view "$PR_NUMBER" --json mergeable | jq -e '.mergeable == true' >/dev/null; then
                echo "Auto-merging PR #$PR_NUMBER"
                gh pr merge "$PR_NUMBER" --auto --merge
              else
                echo "PR #$PR_NUMBER is not auto-mergeable."
              fi

            else
              echo "::error::Install failed. Reverting changes."
              git checkout main
              git branch -D "$BRANCH" || true
              echo "::endgroup::"
              continue
            fi

            git checkout main
            # git branch -D "$BRANCH" || true
            # git push origin --delete "$BRANCH" || true
            echo "::endgroup::"

          done < cask_list.txt
