name: Bump Cartero 
on:
  schedule:
    # Every 24 hours
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  bump-casks:
    runs-on: macos-latest
    steps:
    - uses: macauley/action-homebrew-bump-cask@v1
      with:
        # Required, custom GitHub access token with only the 'public_repo' scope enabled
        token: ${{secrets.TOKEN}}
        # Optional, will create tap repo fork in organization
        org: ORG
        # Bump all outdated casks in this tap
        tap: SoloAntonio/cartero
        # Bump only these casks if outdated
        cask: cartero
        # Optional, if don't want to check for already open PRs
        force: false # true
        # Need to set this input if want to use `brew livecheck`
        livecheck: true
